/* --- DOSA TUTORIAL GAME SCRIPT --- */
(() => {

(()=>{'use strict';const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';const pan={x:507,y:277},base={x:365,y:395},park={x:299,y:332};let state='idle',recipe=null,steps=[],index=-1,elapsed=0,paused=false,last=0,raf=0,tip=true,angle=0,mealCount=0;const durations={dispense:2600,spread:3200,cook:3600,podi:1900,fold:2300,package:3000,deliver:3400};const names={plain:'Plain Dosa',ghee:'Ghee Roast',podi:'Podi Dosa'};const descriptions={dispense:['Ingredient gantry','Metered batter lands on the heating pad.','A measured drizzle follows.'],spread:['Robotic spreading','The central arm follows an outward spiral.','Its spreading tool forms an even dosa.'],cook:['Controlled cooking','The heating pad browns the dosa evenly.','Watch the batter turn crisp and golden.'],podi:['Podi finish','Only this recipe gets a podi topping.','The overhead dispenser shakes it evenly.'],fold:['Precision folding','A thin spatula releases and lifts one half.','The robot folds the dosa without tearing.'],package:['Lift, place, package','The arm transfers the dosa into a tray.','The packaging unit closes the lid.'],deliver:['Circular delivery','The conveyor carries the finished box','to the front pickup window.']};
function attr(id,k,v){$(id).setAttribute(k,v)}function show(id,on){attr(id,'visibility',on?'visible':'hidden')}function svg(tag,a,parent){const e=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));$(parent).append(e);return e}function ease(t){return t*t*(3-2*t)}function mix(a,b,t){return a+(b-a)*t}function moveArm(x,y,rotation=0){const dx=x-base.x,dy=y-base.y,d=Math.hypot(dx,dy),l=130,clamped=Math.min(d,259),h=Math.sqrt(Math.max(0,l*l-clamped*clamped/4)),ex=base.x+dx/2-dy/(d||1)*h,ey=base.y+dy/2+dx/(d||1)*h;const path=`M${base.x} ${base.y}L${ex} ${ey}L${x} ${y}`;['armShadow','armEdge','armBody'].forEach(id=>attr(id,'d',path));attr('elbow','cx',ex);attr('elbow','cy',ey);attr('wrist','cx',x);attr('wrist','cy',y);attr('tool','transform',`translate(${x} ${y}) rotate(${rotation})`)}
for(let i=0;i<64;i++){const a=i*Math.PI*2/64;svg('line',{x1:400+211*Math.cos(a),y1:365+211*Math.sin(a),x2:400+268*Math.cos(a),y2:365+268*Math.sin(a),stroke:'#c4ced8','stroke-width':2},'slats')}for(let i=1;i<8;i++)svg('circle',{cx:507,cy:277,r:i*9.5,fill:'none',stroke:'#d6b987','stroke-width':1.3,opacity:.5},'rings');for(let i=0;i<78;i++){const a=i*2.39996,r=68*Math.sqrt((i+.5)/78);svg('circle',{cx:507+Math.cos(a)*r,cy:277+Math.sin(a)*r,r:1+(i%3)*.5,fill:'#9b622e',opacity:.3},'speckles')}for(let i=0;i<18;i++)svg('circle',{r:3,fill:'#fff0cb',opacity:0},'drops');for(let i=0;i<4;i++)svg('path',{d:'M0 0q-8-12 0-24t0-24',fill:'none',stroke:'#c0c9d0','stroke-width':2,opacity:0},'steam');
function clearScene(){attr('batter','r',0);attr('batter','fill','#fff1d5');attr('rings','opacity',0);attr('speckles','opacity',0);show('folded',false);show('foldTop',false);attr('folded','transform','translate(507 277)');attr('head','transform','translate(0 0)');attr('slats','transform','rotate(0 400 365)');show('box',false);show('boxDosa',false);attr('lid','opacity',0);attr('lidMarks','opacity',0);attr('shutter','height',12);attr('heatRing','opacity',.12);$('drops').childNodes.forEach(e=>e.setAttribute('opacity',0));$('steam').childNodes.forEach(e=>e.setAttribute('opacity',0));moveArm(park.x,park.y);$('panLabel').textContent='Induction cooking pad'}
function updateList(){ $('steps').innerHTML=steps.map((s,i)=>`<li class="${i<index?'done':i===index?'current':''}"><span>${i<index?'✓':i+1}</span>${descriptions[s][0]}</li>`).join('') }
function target(s){return s==='dispense'||s==='podi'?[510,190]:s==='spread'||s==='fold'?[507,277]:s==='cook'?[560,300]:s==='package'?[641,365]:[400,644]}
function enterStep(){elapsed=0;tip=true;state='tutorial';const s=steps[index],d=descriptions[s],t=target(s);$('tutorial').classList.add('visible');document.body.classList.add('teaching');const bx=96,by=s==='deliver'?447:493;attr('callout','transform',`translate(${bx} ${by})`);attr('targetRing','cx',t[0]);attr('targetRing','cy',t[1]);attr('targetDot','cx',t[0]);attr('targetDot','cy',t[1]);attr('leader','d',`M${bx+169} ${by} L${bx+169} ${by-25} L${t[0]} ${t[1]}`);$('tipTag').textContent=`STEP ${index+1} / ${steps.length} · TUTORIAL PAUSE`;$('tipTitle').textContent=d[0];$('tipLine1').textContent=d[1];$('tipLine2').textContent=s==='dispense'?`Then ${recipe==='ghee'?'ghee':'oil'} is dosed for your recipe.`:d[2];attr('tipProgress','width',0);$('current').textContent=d[0];$('detail').textContent=d[1]+' '+(s==='dispense'?`Then ${recipe==='ghee'?'ghee':'oil'} is dosed.`:d[2]);$('status').lastElementChild.textContent='Tutorial pause';updateList()}
function start(key){if(state!=='idle')return;recipe=key;steps=['dispense','spread','cook',...(key==='podi'?['podi']:[]),'fold','package','deliver'];index=0;paused=false;clearScene();$('orderName').textContent=names[key];document.querySelectorAll('.recipe').forEach(b=>{b.disabled=true;b.classList.toggle('selected',b.dataset.recipe===key)});document.querySelectorAll('.chip').forEach(c=>c.classList.toggle('on',['Batter',key==='ghee'?'Ghee':'Oil',...(key==='podi'?['Podi']:[])].includes(c.textContent)));$('pause').disabled=false;enterStep();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(tick)}
function dropParticles(t,fat=false,podi=false){[...$('drops').children].forEach((e,i)=>{const p=(t*5+i/18)%1;const x=podi?pan.x+Math.sin(i*4.3)*62:pan.x+(fat?Math.sin(i)*27:0);e.setAttribute('cx',x);e.setAttribute('cy',mix(197,277,p));e.setAttribute('r',podi?2:fat?2.5:4);e.setAttribute('fill',podi?'#b86828':fat?'#edbe4d':'#fff0d5');e.setAttribute('opacity',.85)})}
function animate(s,t){const smooth=ease(t);$('drops').childNodes.forEach(e=>e.setAttribute('opacity',0));if(s==='dispense'){attr('head','transform',`translate(0 ${mix(0,40,Math.min(t*4,1))})`);if(t>.22){dropParticles(t,t>.72);attr('batter','r',mix(3,31,Math.min((t-.22)/.5,1)))}if(t>.92)attr('head','transform',`translate(0 ${40*(1-(t-.92)/.08)})`)}
if(s==='spread'){const p=Math.max(0,(t-.18)/.82),a=p*Math.PI*8,r=p*68;const x=pan.x+Math.cos(a)*r,y=pan.y+Math.sin(a)*r;if(t<.18)moveArm(mix(park.x,pan.x,ease(t/.18)),mix(park.y,pan.y,ease(t/.18)));else moveArm(x,y,a*180/Math.PI);attr('batter','r',mix(31,76,p));attr('rings','opacity',p);if(t>.93)moveArm(mix(x,park.x,(t-.93)/.07),mix(y,park.y,(t-.93)/.07))}
if(s==='cook'){attr('batter','r',76);attr('batter','fill',`rgb(${Math.round(mix(255,225,t))},${Math.round(mix(241,166,t))},${Math.round(mix(213,65,t))})`);attr('speckles','opacity',t*.8);attr('heatRing','opacity',.4+.3*Math.sin(t*14)**2);$('panLabel').textContent='Browning · '+Math.round(t*100)+'%';[...$('steam').children].forEach((e,i)=>{const p=(t*2+i/4)%1;e.setAttribute('transform',`translate(${465+i*27} ${260-p*45})`);e.setAttribute('opacity',Math.sin(p*Math.PI)*.5)})}
if(s==='podi'){attr('head','transform',`translate(${Math.sin(t*60)*3} 38)`);dropParticles(t,false,true);attr('speckles','opacity',1);if(t>.9)attr('head','transform',`translate(0 ${38*(1-t)/.1})`)}
if(s==='fold'){ $('steam').childNodes.forEach(e=>e.setAttribute('opacity',0));const p=Math.min(t/.35,1);moveArm(mix(park.x,507,ease(p)),mix(park.y,204,ease(p)));if(t>.35){show('folded',true);show('foldTop',true);attr('batter','r',0);attr('rings','opacity',0);attr('speckles','opacity',0);const f=(t-.35)/.65;attr('foldTop','transform',`translate(507 277) scale(1 ${1-2*f})`);moveArm(507,mix(204,302,f));if(t>.98)show('foldTop',false)}}
if(s==='package'){show('box',true);attr('box','transform','translate(640 365)');const p=ease(Math.min(t/.68,1));moveArm(mix(507,640,p),mix(302,355,p),mix(0,65,p));attr('folded','transform',`translate(${mix(507,640,p)} ${mix(277,356,p)}) scale(${mix(1,.36,p)})`);if(t>.68){show('folded',false);show('boxDosa',true);const q=ease((t-.68)/.32);attr('lid','opacity',q);attr('lidMarks','opacity',q);moveArm(mix(640,park.x,q),mix(355,park.y,q))}}
if(s==='deliver'){const travel=Math.min(t/.83,1),a=ease(travel)*Math.PI/2;angle=a*180/Math.PI;attr('slats','transform',`rotate(${angle} 400 365)`);let x=400+240*Math.cos(a),y=365+240*Math.sin(a);if(t>.83){x=400;y=mix(605,675,ease((t-.83)/.17));attr('shutter','height',mix(12,2,(t-.83)/.17))}attr('box','transform',`translate(${x} ${y}) rotate(${angle})`)} }
function tick(now){const dt=Math.min(80,now-last);last=now;if(!paused){elapsed+=dt;if(tip){attr('tipProgress','width',298*Math.min(elapsed/1500,1));if(elapsed>=1500){tip=false;elapsed=0;state='running';$('tutorial').classList.remove('visible');document.body.classList.remove('teaching');$('status').lastElementChild.textContent='Preparing'}}else{const s=steps[index],t=Math.min(elapsed/durations[s],1);animate(s,t);$('overall').style.width=((index+t)/steps.length*100)+'%';if(t>=1){index++;if(index<steps.length)enterStep();else{state='ready';$('status').lastElementChild.textContent='Ready to collect';$('current').textContent=names[recipe]+' is ready.';$('detail').textContent='Your boxed dosa has arrived at the pickup window.';$('collect').hidden=false;$('pause').disabled=true;updateList();return}}}}raf=requestAnimationFrame(tick)}
function reset(){cancelAnimationFrame(raf);state='idle';recipe=null;steps=['dispense','spread','cook','fold','package','deliver'];index=-1;elapsed=0;paused=false;tip=false;clearScene();$('tutorial').classList.remove('visible');document.body.classList.remove('teaching');$('pauseCover').style.display='none';$('pause').disabled=true;$('pause').textContent='Pause';$('collect').hidden=true;$('overall').style.width='0%';$('orderName').textContent='Waiting for your next order';$('status').lastElementChild.textContent='Ready';$('current').textContent='Your kitchen is ready.';$('detail').textContent='Choose a dosa to start the interactive tutorial.';document.querySelectorAll('.recipe').forEach(b=>{b.disabled=false;b.classList.remove('selected')});document.querySelectorAll('.chip').forEach(c=>c.classList.remove('on'));updateList()}
document.querySelectorAll('.recipe').forEach(b=>b.addEventListener('click',()=>start(b.dataset.recipe)));$('reset').addEventListener('click',reset);$('pause').addEventListener('click',()=>{paused=!paused;$('pause').textContent=paused?'Resume':'Pause';$('pauseCover').style.display=paused&&!tip?'block':'none'});$('collect').addEventListener('click',()=>{mealCount++;reset();$('current').textContent='Enjoy your dosa!';$('detail').textContent=`${mealCount} order${mealCount===1?'':'s'} collected. Choose another recipe when you’re ready.`});document.addEventListener('visibilitychange',()=>{last=performance.now()});reset();$('orderName').textContent='Waiting for your first order';})();

})();
